Comment View Controller Refactoring and Documentation Added.
ccrama/Slide-iOS pull request #1052
Opened 2020-08-06 00:51 UTC by UnknownEncrypter

This Pull Request, contains CommentVC being refactored and most importantly documentation added to make it somewhat more readable to other developers. Along with a few other minor fixes.

2020-08-21 19:16 UTC, colejd requested changes
Carlos will do actual review of your logic, but I just found one thing that you should revert.

2020-08-21 19:16 UTC, colejd commented on scripts/install-filter.sh
> +your_usr_id="com.JosiahAgosto" # Anything you want. Sets USR_DOMAIN in the project.
Please don't commit these changes. Since the script is a one-time thing, you can just remove your changes and the automatic substitution will still work.

2020-08-21 19:16 UTC, colejd commented on scripts/install-filter.sh
> +git config filter.filter-credentials.clean "sed -e 's/$your_developer_id/$project_developer_id/' -e 's/$your_usr_id/$project_usr_id/'"
There's a diff but I'm having trouble seeing what's actually different here.

2020-08-21 19:36 UTC, Josiah-Agosto commented on scripts/install-filter.sh
> +your_usr_id="com.JosiahAgosto" # Anything you want. Sets USR_DOMAIN in the project.
Omg, again I committed this. Sorry I'll get this removed again.

2020-08-21 19:38 UTC, Josiah-Agosto commented on scripts/install-filter.sh
> +git config filter.filter-credentials.clean "sed -e 's/$your_developer_id/$project_developer_id/' -e 's/$your_usr_id/$project_usr_id/'"
Hmm, I don't see a difference at all. I'll check it through the project.

2020-08-21 19:45 UTC, Josiah-Agosto commented on scripts/install-filter.sh
> +git config filter.filter-credentials.clean "sed -e 's/$your_developer_id/$project_developer_id/' -e 's/$your_usr_id/$project_usr_id/'"
Changes like this I haven't touched, these must've changed when I pulled. This file also matches with the origin/develop branch. I'll still look into it though.

2020-08-21 19:58 UTC, Josiah-Agosto commented on scripts/install-filter.sh
> +git config filter.filter-credentials.clean "sed -e 's/$your_developer_id/$project_developer_id/' -e 's/$your_usr_id/$project_usr_id/'"
I put the two lines in some sort of text comparing thing and they are identical I just don't know why they are marking them as different.

2020-09-12 00:18 UTC, ccrama reviewed
Great work here! We can discuss on how to merge in the xcodeproj files, and I am assuming the logic is not changed for any of the broken-out Comments classes. Other than that, just a few minor comments I made on a few lines.

Thank you for the PR! Glad to have you on the project.

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +						DevelopmentTeam = FTT89576VQ;
Just flagging some of the signing stuff that needs to be reverted

Needs to be changed back to 68GVUVA6AU

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				USR_WATCHKIT_IDENTIFIER = "$(USR_DOMAIN).redditslide.watchkitapp";
Needs to be reverted back PRODUCT_BUNDLE_IDENTIFIER and USR_WATCHKIT_IDENTIFIER

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "Reddit For Slide WatchKit 2020";
Needs to be reverted back  PROVISIONING_PROFILE_SPECIFIER and PRODUCT_BUNDLE_IDENTIFIER

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				USR_WATCHKIT_IDENTIFIER = "$(USR_DOMAIN).redditslide.watchkitapp";
Should be reverted, debug has a different identifier than prod

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
This should now be 11

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				USR_WATCHKIT_IDENTIFIER = "$(USR_DOMAIN).Slide.debug.watchkitapp.watchkitextension";
Git might be messing up which line this belongs to, but it should be the Open-in-Slide extension

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
Should be reverted to "iPhone Developer"

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
Deployment target should be 11 now

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				USR_BASE_IDENTIFIER = "$(USR_DOMAIN).redditslide.debug";
Debug needs its own identifier, should be changed back to -debug

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
Target should be 11

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				USR_WATCHKIT_IDENTIFIER = "$(USR_DOMAIN).Slide.debug.watchkitapp.watchkitextension";
VALID_ARCHS was an xcode beta bug, but should be reverted back for the final release

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
Should be changed back to "iPhone Developer"

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
Deployment target should be 11

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "Reddit For Slide 2020";
Provisioning profile should be reverted

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = FTT89576VQ;
Development team needs to be reverted

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = FTT89576VQ;
Development team needs to be reverted

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = FTT89576VQ;
Development team needs to be reverted

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = FTT89576VQ;
Development team needs to be reverted

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit.xcodeproj/xcshareddata/xcschemes/Share to Slide.xcscheme
> -      <MacroExpansion>
I believe this is needed for Share to Slide to function, needs testing

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit/Comments/CommentViewController.swift
> +            try session?.getArticles(name, sort: .new, completion: { (result) in
Need to make sure this matches the current behavior

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit/Comments/CommentViewController.swift
> -                                    self.lastY = self.tableView.contentOffset.y
This code is required for the "live mode new comments" bubble to show up. Was this moved? Can't find it in the PR but I might have missed it :)

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit/Comments/CommentViewController.swift
> +        let alert = UIAlertController.init(title: "Really, delete this comment?", message: "", preferredStyle: .alert)
Might be better to title this "Remove your comment permanently?"

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit/Comments/CommentViewController.swift
> +                                           at: UITableView.ScrollPosition.none, animated: false)
This may cause the TableView to not scroll at all if the view is partially visible, should skip to the top of the screen

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit/Comments/CommentViewController.swift
> +    @objc func dismissTopController(_ sender: AnyObject) {
Good point, we should do some more testing here, as the comment VC may be the first child of a NavVC

2020-09-12 00:18 UTC, ccrama commented on Slide for Reddit/PagingCommentViewController.swift
> +            let vc = CommentViewController(submission: submissionDataSource.content[currentIndex + startIndex])
Single is important to this class, need to check to make sure we don't load every comment when the PagingCommentVC appears. We only want to load comments when the user swipes pages (viewDidAppear)

2020-09-12 03:25 UTC, UnknownEncrypter commented
Thank you. I didn't notice so many different things that shouldn't be committed. I will get those fixed as quick as I can.

2020-09-17 20:23 UTC, UnknownEncrypter commented on Slide for Reddit.xcodeproj/xcshareddata/xcschemes/Share to Slide.xcscheme
> -      <MacroExpansion>
I have no clue what this is and how it got removed, I will look further into it.

2020-09-17 21:25 UTC, UnknownEncrypter commented on Slide for Reddit/Comments/CommentViewController.swift
> -                                    self.lastY = self.tableView.contentOffset.y
Hmm, I also didn't see most of this functions changes inside mine either even when I pulled. I just copied the contents of it to mine.

2020-09-17 21:27 UTC, UnknownEncrypter commented on Slide for Reddit.xcodeproj/project.pbxproj
> +				USR_WATCHKIT_IDENTIFIER = "$(USR_DOMAIN).Slide.debug.watchkitapp.watchkitextension";
So it should look like this, "$(USR_DOMAIN).Open-in-Slide.watchkitextension"?

2020-09-18 21:15 UTC, colejd commented on Slide for Reddit.xcodeproj/project.pbxproj
> -				USR_DOMAIN = ccrama.me;
Need to undo this change or the whole build process will fall apart.

2020-09-21 18:35 UTC, UnknownEncrypter commented on Slide for Reddit.xcodeproj/project.pbxproj
> -				USR_DOMAIN = ccrama.me;
I don't know how this changed. I will add it back somehow.

2020-09-21 18:47 UTC, UnknownEncrypter commented on Slide for Reddit.xcodeproj/project.pbxproj
> -				USR_DOMAIN = ccrama.me;
Added it back.

2020-09-21 19:00 UTC, UnknownEncrypter commented on Slide for Reddit.xcodeproj/xcshareddata/xcschemes/Share to Slide.xcscheme
> -      <MacroExpansion>
So I was trying to figure out what and how this was removed, on September 11th, with the commit named "Fixed freezing when exiting some settings menus". I pulled from the remote and from that file macroExpansion was removed, it must've been added back and I didn't pull so I will try to see if updating everything can fix it.

2020-11-03 05:15 UTC, closed without merging